%YAML:1.2
LoaderColorCamera:
  - name: "loader_color"
    metafile_path: "./camera_color.yaml"

NormalColorViewer:
  - name: "color_viewer"
    color_camera: "loader_color"
    renderer_geometry: "renderer_geometry"

RendererGeometry:
  - name: "renderer_geometry"
    bodies: ["ape"]

Body:
  - name: "ape"
    metafile_path: "./ape.yaml"

StaticDetector:
  - name: "ape_static_detector"
    metafile_path: "./detector.yaml"
    body: "ape"
    color_camera: "loader_color"

RegionModel:
  - name: "ape_region_model"
    metafile_path: "./default_model.yaml"
    body: "ape"

RegionModality:
  - name: "ape_region_modality"
    body: "ape"
    color_camera: "loader_color"
    region_model: "ape_region_model"

Optimizer:
  - name: "ape_optimizer"
    modalities: ["ape_region_modality"]

Tracker:
  - name: "tracker"
    viewers: ["color_viewer"]
    detectors: ["ape_static_detector"]
    optimizers: ["ape_optimizer"]